import { Project } from '../types/project';
import { Complaint, HistoricalConstructionRecord, TrafficImpactSuggestion } from '../types/localChecklist';
import { GPRSurvey } from '../types/gpr';
import { DataSourceConfig } from '../types/ingestion';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'TND-001',
    name: 'Nagpur-Wardha 200km Smart Expressway & Subsurface Utility Corridor',
    tenderNumber: 'TND-001',
    description: '[DEMO DATA] 200km regional expressway corridor construction featuring a 5.0m carriageway width and 5.0m deep subsurface utility trench excavation for high-capacity multi-utility pipeline and conduit networks.',
    type: 'Road',
    budget: 1250000000,
    approvedAmount: 1200000000,
    estimatedAmount: 1300000000,
    potentialSaving: 32000000,
    startDate: '2026-09-15',
    expectedCompletionDate: '2027-11-30',
    durationDays: 441,
    status: 'Approved',
    contractor: 'Shapoorji Pallonji Roadworks Ltd',
    department: 'Public Works Department (PWD)',
    authority: 'Nagpur Municipal Corporation & MSRDC',
    managedBy: 'CivicSync',
    locationName: 'Nagpur-Wardha Regional Expressway Corridor',
    wardOrRegion: 'Nagpur-Wardha Expressway Sector',
    latitude: 21.0500,
    longitude: 78.8500,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [78.1000, 20.6000],
        [79.6000, 21.5000],
        [79.6000, 21.5050],
        [78.1000, 20.6050],
        [78.1000, 20.6000]
      ]]
    },
    lengthMeters: 200000,
    widthMeters: 5.0,
    depthMeters: 5.0,
    heightMeters: 0.0,
    material: 'Dense Bituminous Macadam (DBM) & Reinforced Subsurface Ducts',
    constructionMethod: 'Cold Milling, Asphalt Paver & 5m Trench Box Excavation',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 65,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-002',
    name: 'Hingna MIDC 6-Lane Industrial Corridor Road Widening',
    tenderNumber: 'TND-002',
    description: '[DEMO DATA] Heavy-duty reinforced concrete rigid pavement widening with stormwater kerb integration for heavy freight logistics.',
    type: 'Road',
    budget: 184000000,
    approvedAmount: 178000000,
    estimatedAmount: 192000000,
    potentialSaving: 5400000,
    startDate: '2026-10-01',
    expectedCompletionDate: '2027-04-15',
    durationDays: 196,
    status: 'Active',
    contractor: 'L&T Transportation Infrastructure',
    department: 'MIDC Engineering Division',
    authority: 'Maharashtra Industrial Development Corp',
    managedBy: 'CivicSync',
    locationName: 'Hingna MIDC Main Arterial Road',
    wardOrRegion: 'Hingna Industrial Zone',
    latitude: 21.0850,
    longitude: 78.9820,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [78.9750, 21.0800],
        [78.9900, 21.0800],
        [78.9900, 21.0900],
        [78.9750, 21.0900],
        [78.9750, 21.0800]
      ]]
    },
    lengthMeters: 3800,
    widthMeters: 24.0,
    depthMeters: 0.8,
    heightMeters: 0.0,
    material: 'Pavement Quality Concrete (PQC M40)',
    constructionMethod: 'Slipform Concrete Paving Machine',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 48,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-003',
    name: 'Kanhan River Reinforced Concrete Submersible Bridge',
    tenderNumber: 'TND-003',
    description: '[DEMO DATA] Multi-span high-level bridge with bored pile foundations reaching bedrock at 8.5m depth and precast prestressed concrete girders.',
    type: 'Bridge',
    budget: 245000000,
    approvedAmount: 235000000,
    estimatedAmount: 255000000,
    potentialSaving: 6800000,
    startDate: '2026-09-20',
    expectedCompletionDate: '2027-11-30',
    durationDays: 436,
    status: 'Approved',
    contractor: 'Gammon India Bridge Division',
    department: 'State Highway Authority',
    authority: 'Public Works Department',
    managedBy: 'CivicSync',
    locationName: 'Kanhan River Crossing Corridor',
    wardOrRegion: 'Kanhan North',
    latitude: 21.2280,
    longitude: 79.2450,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.2400, 21.2230],
        [79.2520, 21.2230],
        [79.2520, 21.2330],
        [79.2400, 21.2330],
        [79.2400, 21.2230]
      ]]
    },
    lengthMeters: 920,
    widthMeters: 16.0,
    depthMeters: 8.5,
    heightMeters: 12.0,
    material: 'M45 Prestressed Concrete & Steel Girders',
    constructionMethod: 'Cast-in-situ Bored Piling & Segmental Launcher',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 72,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-004',
    name: 'Ramdaspeth Canal Multi-Span Elevated Flyover',
    tenderNumber: 'TND-004',
    description: '[DEMO DATA] Elevated 4-lane flyover superstructure resting on hammerhead concrete pier columns and bored pile caps over Nag River canal.',
    type: 'Bridge',
    budget: 180000000,
    approvedAmount: 175000000,
    estimatedAmount: 190000000,
    potentialSaving: 4500000,
    startDate: '2026-09-20',
    expectedCompletionDate: '2027-05-15',
    durationDays: 237,
    status: 'Active',
    contractor: 'Afcons Infrastructure Projects',
    department: 'Bridge & Flyover Engineering',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'Ramdaspeth Canal Crossing',
    wardOrRegion: 'Ramdaspeth Zone 2',
    latitude: 21.1380,
    longitude: 79.0760,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0710, 21.1330],
        [79.0810, 21.1330],
        [79.0810, 21.1430],
        [79.0710, 21.1430],
        [79.0710, 21.1330]
      ]]
    },
    lengthMeters: 620,
    widthMeters: 18.0,
    depthMeters: 4.5,
    heightMeters: 9.0,
    material: 'Prestressed Concrete Box Girders',
    constructionMethod: 'Precast Segmental Erection',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 62,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-005',
    name: 'YCC Hingna Campus Integrated 7-Story Academic Complex',
    tenderNumber: 'TND-005',
    description: '[DEMO DATA] 7-story institutional facility with reinforced concrete framework, energy-efficient glazed facade, deep basement footing at 4.8m depth, and perimeter stormwater drainage.',
    type: 'Building',
    budget: 640000000,
    approvedAmount: 620000000,
    estimatedAmount: 660000000,
    potentialSaving: 18500000,
    startDate: '2026-10-01',
    expectedCompletionDate: '2028-03-31',
    durationDays: 547,
    status: 'Approved',
    contractor: 'Shapoorji Pallonji Building Division',
    department: 'Higher Education & Institutional Works',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'YCC Campus Corridor, Hingna Road',
    wardOrRegion: 'Hingna Zone',
    latitude: 21.0980,
    longitude: 79.0035,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0000, 21.0940],
        [79.0080, 21.0940],
        [79.0080, 21.1020],
        [79.0000, 21.1020],
        [79.0000, 21.0940]
      ]]
    },
    lengthMeters: 850,
    widthMeters: 45.0,
    depthMeters: 4.8,
    heightMeters: 28.0,
    buildingFloors: 7,
    material: 'M40 Reinforced Concrete & Low-E Glazing',
    constructionMethod: 'Deep Raft Foundation with Pre-engineered Superstructure',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 42,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-006',
    name: 'Sitabuldi Central Smart Municipal Commercial Hub',
    tenderNumber: 'TND-006',
    description: '[DEMO DATA] 9-story commercial complex with 2 underground parking basements, transit plaza connectivity, and centralized HVAC infrastructure.',
    type: 'Building',
    budget: 820000000,
    approvedAmount: 790000000,
    estimatedAmount: 850000000,
    potentialSaving: 22000000,
    startDate: '2026-11-01',
    expectedCompletionDate: '2028-10-31',
    durationDays: 730,
    status: 'Approved',
    contractor: 'Tata Projects Real Estate Infra',
    department: 'Urban Development SPV',
    authority: 'Nagpur Smart City SPV',
    managedBy: 'CivicSync',
    locationName: 'Sitabuldi Main Commercial Hub',
    wardOrRegion: 'Sitabuldi Zone 3',
    latitude: 21.1470,
    longitude: 79.0825,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0780, 21.1430],
        [79.0870, 21.1430],
        [79.0870, 21.1510],
        [79.0780, 21.1510],
        [79.0780, 21.1430]
      ]]
    },
    lengthMeters: 450,
    widthMeters: 60.0,
    depthMeters: 7.2,
    heightMeters: 36.0,
    buildingFloors: 9,
    material: 'Composite Steel-Concrete Frame & ACP',
    constructionMethod: 'Top-Down Basement Excavation & Steel Erection',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 84,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-007',
    name: 'PMAY Urban High-Density Affordable Housing Towers',
    tenderNumber: 'TND-007',
    description: '[DEMO DATA] Quad-tower 12-story residential development for 1,200 families with monolithic aluminum formwork concrete casting.',
    type: 'Building',
    budget: 950000000,
    approvedAmount: 920000000,
    estimatedAmount: 980000000,
    potentialSaving: 28000000,
    startDate: '2026-08-15',
    expectedCompletionDate: '2028-06-30',
    durationDays: 685,
    status: 'Active',
    contractor: 'NCC Urban Infrastructure',
    department: 'Housing & Slum Rehabilitation',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'Wathoda Urban Housing Sector',
    wardOrRegion: 'Nehru Nagar Zone 6',
    latitude: 21.1250,
    longitude: 79.1350,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.1300, 21.1200],
        [79.1410, 21.1200],
        [79.1410, 21.1300],
        [79.1300, 21.1300],
        [79.1300, 21.1200]
      ]]
    },
    lengthMeters: 600,
    widthMeters: 80.0,
    depthMeters: 5.5,
    heightMeters: 42.0,
    buildingFloors: 12,
    material: 'Monolithic M35 Concrete via Mivan Formwork',
    constructionMethod: 'Automated Formwork Rapid Casting',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 55,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-008',
    name: 'Transit-Oriented Mixed-Use Commercial & Residential Quad',
    tenderNumber: 'TND-008',
    description: '[DEMO DATA] Integrated retail arcade, office suites, and serviced apartments directly linked to metro concourse level.',
    type: 'Building',
    budget: 740000000,
    approvedAmount: 710000000,
    estimatedAmount: 770000000,
    potentialSaving: 19500000,
    startDate: '2026-10-15',
    expectedCompletionDate: '2028-08-31',
    durationDays: 686,
    status: 'Approved',
    contractor: 'Godrej Properties Infra JV',
    department: 'Urban SPV Planning',
    authority: 'Maha Metro Rail Corporation',
    managedBy: 'CivicSync',
    locationName: 'Munje Square Transit Corridor',
    wardOrRegion: 'Sitabuldi Zone 3',
    latitude: 21.1455,
    longitude: 79.0865,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0820, 21.1420],
        [79.0910, 21.1420],
        [79.0910, 21.1500],
        [79.0820, 21.1500],
        [79.0820, 21.1420]
      ]]
    },
    lengthMeters: 380,
    widthMeters: 55.0,
    depthMeters: 6.0,
    heightMeters: 32.0,
    buildingFloors: 8,
    material: 'Precast Concrete & Solar Glass Envelopes',
    constructionMethod: 'Integrated Foundation Piles & Modular Superstructure',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 68,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-009',
    name: 'Medical Square - Panchsheel Precast Stormwater Box Culvert',
    tenderNumber: 'TND-009',
    description: '[DEMO DATA] Heavy-duty 2400x1800mm reinforced concrete box culvert to mitigate severe monsoon flooding along commercial arterial.',
    type: 'Drainage',
    budget: 152000000,
    approvedAmount: 148000000,
    estimatedAmount: 160000000,
    potentialSaving: 2100000,
    startDate: '2026-08-10',
    expectedCompletionDate: '2027-01-20',
    durationDays: 163,
    status: 'Active',
    contractor: 'Gammon India Civil Works',
    department: 'Stormwater Drainage Department',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'Medical Square Canal Corridor',
    wardOrRegion: 'Dhantoli Zone 4',
    latitude: 21.1350,
    longitude: 79.0920,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0870, 21.1300],
        [79.0970, 21.1300],
        [79.0970, 21.1400],
        [79.0870, 21.1400],
        [79.0870, 21.1300]
      ]]
    },
    lengthMeters: 1820,
    widthMeters: 3.2,
    depthMeters: 3.2,
    heightMeters: 0.0,
    material: 'M40 Precast Reinforced Concrete Box',
    constructionMethod: 'Heavy Crane Segmental Trench Placement',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 74,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-010',
    name: 'Civil Lines Underground Power Grid Conversion (33kV XLPE)',
    tenderNumber: 'TND-010',
    description: '[DEMO DATA] Underground conversion of overhead lines into concrete-encased 33kV high tension XLPE power cable trenches.',
    type: 'Electrical',
    budget: 42000000,
    approvedAmount: 41000000,
    estimatedAmount: 43500000,
    potentialSaving: 600000,
    startDate: '2026-10-01',
    expectedCompletionDate: '2026-12-30',
    durationDays: 90,
    status: 'Pending',
    contractor: 'KEC International Ltd',
    department: 'MSEDCL Distribution Division',
    authority: 'Maharashtra State Electricity Distribution Co.',
    managedBy: 'CivicSync',
    locationName: 'Temple Road, Civil Lines',
    wardOrRegion: 'Civil Lines Zone 1',
    latitude: 21.1550,
    longitude: 79.0720,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0680, 21.1500],
        [79.0770, 21.1500],
        [79.0770, 21.1600],
        [79.0680, 21.1600],
        [79.0680, 21.1500]
      ]]
    },
    lengthMeters: 1480,
    widthMeters: 1.2,
    depthMeters: 1.8,
    heightMeters: 0.0,
    material: '33kV Cross-linked Polyethylene (XLPE) Copper Cable',
    constructionMethod: 'Trench Excavation with Concrete Warning Tiles',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 38,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-011',
    name: 'Dharampeth High-Pressure 600mm DI K9 Water Transmission Main',
    tenderNumber: 'TND-011',
    description: '[DEMO DATA] Continuous water transmission main laid at 5.0m depth with automated air valves and electromagnetic flow meters.',
    type: 'Water',
    budget: 84000000,
    approvedAmount: 82500000,
    estimatedAmount: 89000000,
    potentialSaving: 1450000,
    startDate: '2026-09-01',
    expectedCompletionDate: '2026-12-15',
    durationDays: 105,
    status: 'Active',
    contractor: 'L&T Infrastructure Water Division',
    department: 'Water Works Department (NMC)',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'West High Court Road, Dharampeth',
    wardOrRegion: 'Dharampeth Zone 2',
    latitude: 21.1442,
    longitude: 79.0628,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0570, 21.1390],
        [79.0690, 21.1390],
        [79.0690, 21.1500],
        [79.0570, 21.1500],
        [79.0570, 21.1390]
      ]]
    },
    lengthMeters: 2100,
    widthMeters: 3.5,
    depthMeters: 5.0,
    heightMeters: 0.0,
    diameterMm: 600,
    material: 'Ductile Iron (K9)',
    constructionMethod: 'Open Cut Trench & Micro-tunneling at junctions',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 68,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-012',
    name: 'Sitabuldi Deep Sewer Trunk Line Rehabilitation (6.2m Depth)',
    tenderNumber: 'TND-012',
    description: '[DEMO DATA] Deep excavation replacement of collapsed brick sewer with 900mm NP4 reinforced concrete Hume pipes and drop manholes.',
    type: 'Sewerage',
    budget: 98000000,
    approvedAmount: 95000000,
    estimatedAmount: 104000000,
    potentialSaving: 1100000,
    startDate: '2026-07-01',
    expectedCompletionDate: '2026-11-15',
    durationDays: 137,
    status: 'Delayed',
    contractor: 'Patel Infrastructure Joint Venture',
    department: 'Sewerage & Sanitation Board',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'Other',
    locationName: 'Temple Bazar Corridor, Sitabuldi',
    wardOrRegion: 'Sitabuldi Zone 3',
    latitude: 21.1465,
    longitude: 79.0830,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0780, 21.1420],
        [79.0880, 21.1420],
        [79.0880, 21.1510],
        [79.0780, 21.1510],
        [79.0780, 21.1420]
      ]]
    },
    lengthMeters: 1250,
    widthMeters: 2.8,
    depthMeters: 6.2,
    heightMeters: 0.0,
    diameterMm: 900,
    material: 'Reinforced Concrete (NP4) with Epoxy Coating',
    constructionMethod: 'Sheet Piling & Deep Excavation with Dewatering',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 91,
    collaborationPotential: 'Conflict Alert'
  },
  {
    id: 'TND-013',
    name: 'Nagpur Metro Line 2 Feeder Viaduct & Substructure',
    tenderNumber: 'TND-013',
    description: '[DEMO DATA] Elevated metro viaduct pier foundations, track slab casting, and electrical substations on Wardha Road.',
    type: 'Bridge',
    budget: 450000000,
    approvedAmount: 430000000,
    estimatedAmount: 470000000,
    potentialSaving: 12000000,
    startDate: '2026-09-01',
    expectedCompletionDate: '2028-02-28',
    durationDays: 545,
    status: 'Active',
    contractor: 'Afcons - Vijeta Metro JV',
    department: 'Metro Civil Engineering',
    authority: 'Maha Metro Rail Corporation',
    managedBy: 'CivicSync',
    locationName: 'Wardha Road Metro Corridor',
    wardOrRegion: 'Dhantoli Zone 4',
    latitude: 21.1210,
    longitude: 79.0750,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0680, 21.1150],
        [79.0820, 21.1150],
        [79.0820, 21.1270],
        [79.0680, 21.1270],
        [79.0680, 21.1150]
      ]]
    },
    lengthMeters: 2400,
    widthMeters: 12.0,
    depthMeters: 10.0,
    heightMeters: 14.5,
    material: 'Precast Segmental Viaduct & Steel Truss Spans',
    constructionMethod: 'Overhead Launching Gantry & Deep Piling',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 60,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-014',
    name: 'Kasturchand Park Integrated Public Amphitheatre & Civic Plaza',
    tenderNumber: 'TND-014',
    description: '[DEMO DATA] Heritage urban plaza restoration, stepped seating amphitheatre, subterranean rainwater harvesting sump, and architectural lighting.',
    type: 'Building',
    budget: 110000000,
    approvedAmount: 105000000,
    estimatedAmount: 115000000,
    potentialSaving: 3200000,
    startDate: '2026-10-01',
    expectedCompletionDate: '2027-06-30',
    durationDays: 272,
    status: 'Approved',
    contractor: 'Heritage Urban Landscapes Ltd',
    department: 'Smart City Heritage Conservation',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'Kasturchand Park Grounds',
    wardOrRegion: 'Civil Lines Zone 1',
    latitude: 21.1520,
    longitude: 79.0850,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0800, 21.1480],
        [79.0900, 21.1480],
        [79.0900, 21.1560],
        [79.0800, 21.1560],
        [79.0800, 21.1480]
      ]]
    },
    lengthMeters: 550,
    widthMeters: 65.0,
    depthMeters: 3.5,
    heightMeters: 10.0,
    buildingFloors: 2,
    material: 'Natural Basalt Stone, Corten Steel & Tensile Fabric Canopies',
    constructionMethod: 'Stone Masonry & Subterranean Sump Chamber',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 30,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-015',
    name: 'Government Polytechnic Advanced STEM & Robotics Lab Complex',
    tenderNumber: 'TND-015',
    description: '[DEMO DATA] 5-story research and robotics laboratory building with seismic vibration isolation pads and high-capacity electrical riser ducts.',
    type: 'Building',
    budget: 320000000,
    approvedAmount: 310000000,
    estimatedAmount: 330000000,
    potentialSaving: 8500000,
    startDate: '2026-09-01',
    expectedCompletionDate: '2027-12-31',
    durationDays: 486,
    status: 'Approved',
    contractor: 'B.G. Shirke Construction Technology',
    department: 'Technical Education Works',
    authority: 'Directorate of Technical Education',
    managedBy: 'CivicSync',
    locationName: 'Sadar Polytechnic Campus',
    wardOrRegion: 'Mangalwari Zone 10',
    latitude: 21.1620,
    longitude: 79.0780,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0730, 21.1570],
        [79.0830, 21.1570],
        [79.0830, 21.1670],
        [79.0730, 21.1670],
        [79.0730, 21.1570]
      ]]
    },
    lengthMeters: 320,
    widthMeters: 35.0,
    depthMeters: 4.2,
    heightMeters: 20.0,
    buildingFloors: 5,
    material: 'Precast Concrete Wall Panels & Insulated Glazing',
    constructionMethod: 'Prefabricated Structural Assembly',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 40,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-016',
    name: 'AIIMS Trauma Care Hospital & Subsurface Oxygen Tank Vault',
    tenderNumber: 'TND-016',
    description: '[DEMO DATA] Specialized 6-story trauma hospital wing with cryogenic medical oxygen underground vault and helipad rooftop.',
    type: 'Building',
    budget: 580000000,
    approvedAmount: 560000000,
    estimatedAmount: 600000000,
    potentialSaving: 14000000,
    startDate: '2026-08-01',
    expectedCompletionDate: '2028-01-31',
    durationDays: 548,
    status: 'Active',
    contractor: 'Ahluwalia Contracts India Ltd',
    department: 'Ministry of Health Infrastructure',
    authority: 'AIIMS Engineering Cell',
    managedBy: 'CivicSync',
    locationName: 'AIIMS MIHAN Campus',
    wardOrRegion: 'MIHAN SEZ',
    latitude: 21.0560,
    longitude: 79.0340,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0280, 21.0500],
        [79.0400, 21.0500],
        [79.0400, 21.0620],
        [79.0280, 21.0620],
        [79.0280, 21.0500]
      ]]
    },
    lengthMeters: 500,
    widthMeters: 50.0,
    depthMeters: 6.5,
    heightMeters: 25.0,
    buildingFloors: 6,
    material: 'Radiation-Shielded Concrete & Antibacterial Wall Cladding',
    constructionMethod: 'Heavy Raft Foundation & Cleanroom Construction',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 50,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-017',
    name: 'Sitabuldi 5-Story Underground Automated Robotic Car Park',
    tenderNumber: 'TND-017',
    description: '[DEMO DATA] Subterranean robotic parking silo accommodating 650 vehicles to clear surface road congestion around Market Square.',
    type: 'Building',
    budget: 290000000,
    approvedAmount: 280000000,
    estimatedAmount: 300000000,
    potentialSaving: 7500000,
    startDate: '2026-11-15',
    expectedCompletionDate: '2028-05-30',
    durationDays: 562,
    status: 'Approved',
    contractor: 'Simplex Infrastructures Ltd',
    department: 'Smart City Parking SPV',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'Market Square, Sitabuldi',
    wardOrRegion: 'Sitabuldi Zone 3',
    latitude: 21.1460,
    longitude: 79.0845,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0800, 21.1420],
        [79.0890, 21.1420],
        [79.0890, 21.1500],
        [79.0800, 21.1500],
        [79.0800, 21.1420]
      ]]
    },
    lengthMeters: 180,
    widthMeters: 40.0,
    depthMeters: 9.8,
    heightMeters: 3.5,
    material: 'Reinforced Concrete Diaphragm Walls & Steel Palette Lifts',
    constructionMethod: 'Deep Diaphragm Wall Excavation & Secant Piling',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 78,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-018',
    name: 'Butibori Industrial Logistics Warehouse & Sump Facility',
    tenderNumber: 'TND-018',
    description: '[DEMO DATA] Pre-engineered steel warehouse building with high-load laser-screed floor slabs and 2,000 m³ industrial water treatment sump.',
    type: 'Building',
    budget: 210000000,
    approvedAmount: 200000000,
    estimatedAmount: 220000000,
    potentialSaving: 5100000,
    startDate: '2026-09-10',
    expectedCompletionDate: '2027-06-15',
    durationDays: 278,
    status: 'Active',
    contractor: 'Kirby Building Systems',
    department: 'Industrial Infrastructure Board',
    authority: 'MIDC',
    managedBy: 'CivicSync',
    locationName: 'Butibori Industrial Area Phase 2',
    wardOrRegion: 'Butibori Zone',
    latitude: 20.9230,
    longitude: 79.0080,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0000, 21.9180],
        [79.0160, 21.9180],
        [79.0160, 21.9280],
        [79.0000, 21.9280],
        [79.0000, 21.9180]
      ]]
    },
    lengthMeters: 650,
    widthMeters: 90.0,
    depthMeters: 4.0,
    heightMeters: 14.0,
    material: 'High-Tensile Structural Steel & PUF Insulated Panels',
    constructionMethod: 'Pre-Engineered Building (PEB) Fast Track Erection',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 35,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-019',
    name: 'Samruddhi Expressway Junction Grade Separator & Cloverleaf',
    tenderNumber: 'TND-019',
    description: '[DEMO DATA] High-speed cloverleaf interchange with dual-span composite overbridges, soil nail embankment retention, and smart toll gantries.',
    type: 'Bridge',
    budget: 520000000,
    approvedAmount: 500000000,
    estimatedAmount: 540000000,
    potentialSaving: 16000000,
    startDate: '2026-08-20',
    expectedCompletionDate: '2028-02-15',
    durationDays: 544,
    status: 'Active',
    contractor: 'MEP Infrastructure Developers',
    department: 'MSRDC Highways',
    authority: 'Maharashtra State Road Development Corp',
    managedBy: 'CivicSync',
    locationName: 'Nagpur-Mumbai Expressway Interchange',
    wardOrRegion: 'Hingna Outer Corridor',
    latitude: 21.0420,
    longitude: 78.9650,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [78.9550, 21.0350],
        [78.9750, 21.0350],
        [78.9750, 21.0490],
        [78.9550, 21.0490],
        [78.9550, 21.0350]
      ]]
    },
    lengthMeters: 3200,
    widthMeters: 32.0,
    depthMeters: 5.0,
    heightMeters: 11.5,
    material: 'Reinforced Earth (RE) Retaining Walls & Steel Plate Girders',
    constructionMethod: 'Heavy Earthmoving & Girder Launching',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 66,
    collaborationPotential: 'Medium'
  },
  {
    id: 'TND-020',
    name: 'RBI Square Smart Signalized Multi-Level Underpass',
    tenderNumber: 'TND-020',
    description: '[DEMO DATA] Grade-separated vehicle underpass box and pedestrian subway with integrated LED traffic intelligence sensing.',
    type: 'Road',
    budget: 165000000,
    approvedAmount: 160000000,
    estimatedAmount: 172000000,
    potentialSaving: 4800000,
    startDate: '2026-10-01',
    expectedCompletionDate: '2027-08-30',
    durationDays: 333,
    status: 'Approved',
    contractor: 'J. Kumar Infraprojects',
    department: 'Traffic Engineering Cell',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'RBI Square, Central Nagpur',
    wardOrRegion: 'Civil Lines Zone 1',
    latitude: 21.1505,
    longitude: 79.0790,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0740, 21.1460],
        [79.0840, 21.1460],
        [79.0840, 21.1550],
        [79.0740, 21.1460]
      ]]
    },
    lengthMeters: 680,
    widthMeters: 18.0,
    depthMeters: 5.8,
    heightMeters: 0.0,
    material: 'Reinforced Concrete Cut-and-Cover Underpass Box',
    constructionMethod: 'Cut & Cover with Temporary Decking for Traffic',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 82,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-021',
    name: 'Ambazari Lake Pedestrian Cable-Stayed Suspension Footbridge',
    tenderNumber: 'TND-021',
    description: '[DEMO DATA] 240m signature cable-stayed pedestrian bridge with 34m single inclined steel pylon and architectural timber decking over lake inlet.',
    type: 'Bridge',
    budget: 95000000,
    approvedAmount: 92000000,
    estimatedAmount: 99000000,
    potentialSaving: 2400000,
    startDate: '2026-09-01',
    expectedCompletionDate: '2027-07-31',
    durationDays: 333,
    status: 'Approved',
    contractor: 'Schwing Stetter Specialized Civil',
    department: 'Lake Rejuvenation & Tourism SPV',
    authority: 'Nagpur Smart City SPV',
    managedBy: 'CivicSync',
    locationName: 'Ambazari Lake Promenade',
    wardOrRegion: 'Dharampeth Zone 2',
    latitude: 21.1310,
    longitude: 79.0490,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0430, 21.1260],
        [79.0550, 21.1260],
        [79.0550, 21.1360],
        [79.0430, 21.1260]
      ]]
    },
    lengthMeters: 240,
    widthMeters: 4.5,
    depthMeters: 6.0,
    heightMeters: 34.0,
    material: 'High-Tensile Galvanized Stay Cables & Steel Deck',
    constructionMethod: 'Pylon Anchor Drilling & Cable Tuning',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 35,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-022',
    name: 'Futala Lake Deep Pier Caisson Footings & Water Screen Foundation',
    tenderNumber: 'TND-022',
    description: '[DEMO DATA] Subaqueous heavy reinforced concrete caissons sunk 7.5m into lake bedrock for multimedia water fountain installation.',
    type: 'Bridge',
    budget: 135000000,
    approvedAmount: 130000000,
    estimatedAmount: 142000000,
    potentialSaving: 3800000,
    startDate: '2026-07-15',
    expectedCompletionDate: '2027-03-31',
    durationDays: 259,
    status: 'Active',
    contractor: 'Bauer Engineering India Piling',
    department: 'Waterfront Development Authority',
    authority: 'Nagpur Municipal Corporation',
    managedBy: 'CivicSync',
    locationName: 'Futala Lake Central Waterfront',
    wardOrRegion: 'Dharampeth Zone 2',
    latitude: 21.1540,
    longitude: 79.0450,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0390, 21.1490],
        [79.0510, 21.1490],
        [79.0510, 21.1590],
        [79.0390, 21.1490]
      ]]
    },
    lengthMeters: 350,
    widthMeters: 12.0,
    depthMeters: 7.5,
    heightMeters: 4.5,
    material: 'Sulfate-Resistant Underwater M40 Concrete',
    constructionMethod: 'Open Caisson Sinking & Tremie Concrete Pouring',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 58,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-023',
    name: 'Seminary Hills Watershed Terracing & Slope Retention Wall',
    tenderNumber: 'TND-023',
    description: '[DEMO DATA] Stepped gabion retaining wall system, geo-grid slope stabilization, and deep soil anchor nails to prevent hillside landslides.',
    type: 'Drainage',
    budget: 78000000,
    approvedAmount: 75000000,
    estimatedAmount: 82000000,
    potentialSaving: 1900000,
    startDate: '2026-10-01',
    expectedCompletionDate: '2027-04-30',
    durationDays: 211,
    status: 'Approved',
    contractor: 'Maccaferri Environmental Solutions',
    department: 'Soil Conservation & Forest Infrastructure',
    authority: 'State Forest Department',
    managedBy: 'CivicSync',
    locationName: 'Seminary Hills Slopes',
    wardOrRegion: 'Civil Lines Zone 1',
    latitude: 21.1650,
    longitude: 79.0590,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0530, 21.1600],
        [79.0650, 21.1600],
        [79.0650, 21.1700],
        [79.0530, 21.1600]
      ]]
    },
    lengthMeters: 1100,
    widthMeters: 20.0,
    depthMeters: 4.0,
    heightMeters: 8.0,
    material: 'Rock Gabion Mattresses & High-Tensile Steel Mesh',
    constructionMethod: 'Drilled Soil Nailing & Shotcreting',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 25,
    collaborationPotential: 'Low'
  },
  {
    id: 'TND-024',
    name: 'Zero Mile Smart Urban Governance Quadrangle Complex',
    tenderNumber: 'TND-024',
    description: '[DEMO DATA] 8-story central command and municipal data center building with redundant power substations and subterranean fiber interconnect vaults.',
    type: 'Building',
    budget: 720000000,
    approvedAmount: 690000000,
    estimatedAmount: 750000000,
    potentialSaving: 21000000,
    startDate: '2026-09-15',
    expectedCompletionDate: '2028-09-30',
    durationDays: 746,
    status: 'Active',
    contractor: 'L&T Construction Buildings Division',
    department: 'Smart City Mission',
    authority: 'Nagpur Smart City SPV',
    managedBy: 'CivicSync',
    locationName: 'Zero Mile Monument Precinct',
    wardOrRegion: 'Civil Lines Zone 1',
    latitude: 21.1490,
    longitude: 79.0815,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0760, 21.1440],
        [79.0870, 21.1440],
        [79.0870, 21.1540],
        [79.0760, 21.1440]
      ]]
    },
    lengthMeters: 420,
    widthMeters: 55.0,
    depthMeters: 6.8,
    heightMeters: 32.0,
    buildingFloors: 8,
    material: 'Seismic Grade Steel Framework & Double Glazed Curtain Walls',
    constructionMethod: 'Deep Basements & Composite Structural Framing',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 70,
    collaborationPotential: 'High'
  },
  {
    id: 'TND-025',
    name: 'Nag River Rejuvenation, Retaining Embankment & Sewage Interceptor',
    tenderNumber: 'TND-025',
    description: '[DEMO DATA] 1,400mm trunk sewage interceptor laid parallel to riverbank at 5.5m depth with concrete flood retaining wall along 4.2 km corridor.',
    type: 'Sewerage',
    budget: 380000000,
    approvedAmount: 365000000,
    estimatedAmount: 395000000,
    potentialSaving: 11500000,
    startDate: '2026-08-01',
    expectedCompletionDate: '2028-04-30',
    durationDays: 638,
    status: 'Active',
    contractor: 'Dredging Corporation - Gammon JV',
    department: 'River Rejuvenation Directorate',
    authority: 'National River Conservation Directorate',
    managedBy: 'CivicSync',
    locationName: 'Nag River Central Corridor',
    wardOrRegion: 'Dharampeth to Sitabuldi Basin',
    latitude: 21.1390,
    longitude: 79.0720,
    areaPolygon: {
      type: 'Polygon',
      coordinates: [[
        [79.0640, 21.1340],
        [79.0800, 21.1340],
        [79.0800, 21.1440],
        [79.0640, 21.1340]
      ]]
    },
    lengthMeters: 4200,
    widthMeters: 15.0,
    depthMeters: 5.5,
    heightMeters: 4.0,
    diameterMm: 1400,
    material: 'Reinforced Concrete (NP4) Sewer & Reinforced Stone Embankment',
    constructionMethod: 'Riverbank Sheet Piling & Trench Excavation',
    documents: [],
    source: 'CivicSync Central Tender Registry',
    lastUpdated: '2026-08-16',
    confidence: 'Verified Data',
    riskScore: 88,
    collaborationPotential: 'Conflict Alert'
  }
];

export const INITIAL_REGIONAL_HISTORY: HistoricalConstructionRecord[] = [
  {
    id: 'hist-001',
    projectName: 'Dharampeth Underground Gas Pipeline Phase 1',
    year: 2024,
    wardOrRegion: 'Dharampeth Zone 2',
    locationName: 'West High Court Road, Dharampeth',
    department: 'Maharashtra Natural Gas Ltd (MNGL)',
    contractor: 'Torrent Gas Infra Corp',
    budget: 34000000,
    status: 'Completed',
    knownIssues: ['Trench subsidence near Shankar Nagar Square', 'Asphalt cracking post-monsoon 2024'],
    inspectionSummary: 'Gas pipeline commissioned successfully at 1.8m depth. Note: Left-hand footpath soil uncompacted.',
    depthMeters: 1.8,
    type: 'Gas Pipeline'
  },
  {
    id: 'hist-002',
    projectName: 'Ramdaspeth Stormwater Channel Relining',
    year: 2023,
    wardOrRegion: 'Ramdaspeth Zone 2',
    locationName: 'Canal Road, Ramdaspeth',
    department: 'Stormwater Drainage Department',
    contractor: 'Nagpur Civil Works Pvt Ltd',
    budget: 18500000,
    status: 'Completed',
    knownIssues: ['Heavy siltation during peak July rainfall'],
    inspectionSummary: 'Reinforced shotcrete lining applied along 850m channel.',
    depthMeters: 2.5,
    type: 'Drainage'
  },
  {
    id: 'hist-003',
    projectName: 'Sitabuldi Metro Pillar Underground Foundations',
    year: 2022,
    wardOrRegion: 'Sitabuldi Zone 3',
    locationName: 'Munje Square to Variety Square',
    department: 'Maha Metro Rail Corporation',
    contractor: 'Afcons - Vijeta JV',
    budget: 95000000,
    status: 'Completed',
    knownIssues: ['Punctured unmapped 300mm water main at Variety Square during pile drilling'],
    inspectionSummary: 'Deep pile caps resting on bedrock at 12m depth. Detailed utility map archived.',
    depthMeters: 12.0,
    type: 'Metro Substructure'
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'comp-101',
    title: 'Severe Road Subsidence & Open Trench Near Shankar Nagar Square',
    description: 'Excavation trench dug for water pipe left without barricades or warning lights. Dangerous for two-wheelers at night.',
    category: 'Uncovered Trench / Safety Hazard',
    locationName: 'Shankar Nagar Square, Dharampeth',
    latitude: 21.1402,
    longitude: 79.0662,
    projectId: 'TND-011',
    projectName: 'Dharampeth High-Pressure 600mm DI K9 Water Transmission Main',
    date: '2026-08-14',
    reporterName: 'Anand Kulkarni',
    reporterRole: 'Citizen',
    status: 'In Progress',
    urgency: 'Critical',
    assignedDepartment: 'Water Works Department (NMC)',
    assignedOfficer: 'Er. Rajesh Deshmukh (EE-Water)',
    resolutionNotes: 'Site engineer instructed to install hard barricading and solar flashing hazard lamps within 4 hours.'
  },
  {
    id: 'comp-102',
    title: 'Water Leakage Flooding Commercial Footpaths on WHC Road',
    description: 'High-pressure clean water spraying from test joint near Coffee House square, flooding pedestrian walkway.',
    category: 'Water Leakage / Pipe Burst',
    locationName: 'Near Coffee House, WHC Road',
    latitude: 21.1448,
    longitude: 79.0620,
    projectId: 'TND-011',
    projectName: 'Dharampeth High-Pressure 600mm DI K9 Water Transmission Main',
    date: '2026-08-15',
    reporterName: 'Sunil Verma',
    reporterRole: 'Citizen',
    status: 'Under Review',
    urgency: 'High',
    assignedDepartment: 'Water Works Department (NMC)'
  },
  {
    id: 'comp-103',
    title: 'Heavy Traffic Bottleneck Due to Concurrent Road & Sewer Work',
    description: 'Both Sitabuldi Main road and Dharampeth corridor experiencing severe congestion due to uncoordinated lane blocks.',
    category: 'Traffic Congestion / Blockade',
    locationName: 'Variety Square to Shankar Nagar Arterial',
    latitude: 21.1460,
    longitude: 79.0750,
    date: '2026-08-16',
    reporterName: 'Inspector Patil',
    reporterRole: 'Traffic Police',
    status: 'Assigned',
    urgency: 'High',
    assignedDepartment: 'Traffic Planning Cell'
  }
];

export const INITIAL_TRAFFIC_SUGGESTIONS: TrafficImpactSuggestion[] = [
  {
    id: 'trf-001',
    affectedRoad: 'West High Court Road (Shankar Nagar to Law College)',
    ward: 'Dharampeth Zone 2',
    currentCongestionLevel: 'Heavy',
    potentialDelayMinutes: 22,
    bottleneckPoints: ['Shankar Nagar Square', 'Coffee House Square', 'Dharampeth Tower T-Junction'],
    suggestedConcept: 'One-Way Traffic Management',
    conceptDetails: 'Implement Northbound-only one-way traffic on WHC Road during 08:00–21:00. Divert Southbound vehicles via Canal Road and North Ambazari Road.',
    alternativeRoutes: [
      {
        routeName: 'Route Alpha: Via North Ambazari Boulevard',
        distanceDeltaKm: 0.8,
        estimatedTimeMin: 7,
        recommendedVehicleTypes: ['Buses', 'Commercial Trucks', 'Cars', 'Two-Wheelers']
      },
      {
        routeName: 'Route Beta: Via VIP Road & Civil Lines Bypass',
        distanceDeltaKm: 1.2,
        estimatedTimeMin: 9,
        recommendedVehicleTypes: ['Emergency Vehicles', 'Cars', 'Two-Wheelers']
      }
    ]
  },
  {
    id: 'trf-002',
    affectedRoad: 'Sitabuldi Main Temple Bazar Corridor',
    ward: 'Sitabuldi Zone 3',
    currentCongestionLevel: 'Severe',
    potentialDelayMinutes: 35,
    bottleneckPoints: ['Munje Square', 'Jhansi Rani Square'],
    suggestedConcept: 'Phased Night-Shift Excavation',
    conceptDetails: 'Mandate deep sewer trench excavation strictly between 23:00 and 06:00. Plate open trenches with heavy steel road plates during daytime peak hours.',
    alternativeRoutes: [
      {
        routeName: 'Route Gamma: Via Cotton Market Overbridge',
        distanceDeltaKm: 1.5,
        estimatedTimeMin: 12,
        recommendedVehicleTypes: ['All Heavy & Commercial Vehicles']
      }
    ]
  }
];

export const INITIAL_GPR_SURVEYS: GPRSurvey[] = [
  {
    id: 'gpr-001',
    surveyName: 'Dharampeth WHC Corridor Subsurface 400MHz Survey',
    fileName: 'Dharampeth_WHC_Survey_2026_08.dzt',
    fileSizeBytes: 48500000,
    surveyDate: '2026-08-04',
    wardOrRegion: 'Dharampeth Zone 2',
    surveyor: 'Geovision Advanced Radar Surveys Ltd',
    radarFrequencyMhz: 400,
    maxDepthScannedMeters: 8.0,
    status: 'Processed',
    notes: 'Detected unmapped vintage cast-iron gas mains and 11kV electrical duct crossing at Coffee House Square.',
    anomalies: [
      {
        id: 'anom-1',
        name: 'Unmapped 150mm Metal Line (Possible Gas Feeder)',
        type: 'Metallic Utility',
        depthMeters: 2.1,
        latitude: 21.1440,
        longitude: 79.0630,
        confidence: 92,
        dielectricConstant: 6.2,
        description: 'Strong continuous hyperbolic radar reflection indicating pressurized metal pipe running diagonally across proposed trench.'
      },
      {
        id: 'anom-2',
        name: 'High-Dielectric Subsurface Void / Soil Cavity',
        type: 'Void / Cavity',
        depthMeters: 3.4,
        latitude: 21.1455,
        longitude: 79.0615,
        confidence: 84,
        dielectricConstant: 1.0,
        description: 'Significant amplitude reversal signal indicating subsurface soil erosion cavity under existing road sub-base.'
      },
      {
        id: 'anom-3',
        name: 'Historic Brick Masonry Culvert',
        type: 'Concrete Structure',
        depthMeters: 4.6,
        latitude: 21.1468,
        longitude: 79.0602,
        confidence: 88,
        description: 'Arch-shaped structural boundary consistent with pre-1970 brick masonry drainage structure.'
      }
    ]
  }
];

export const INITIAL_DATA_SOURCES: DataSourceConfig[] = [
  {
    id: 'ds-01',
    name: 'Maharashtra State E-Tenders API (MahaTenders)',
    url: 'https://api.mahatenders.gov.in/v2/municipal/tenders',
    type: 'REST',
    authType: 'API Key',
    endpoint: '/nagpur/active',
    updateFrequency: 'Daily',
    lastSynchronized: '2026-08-16 04:00:00',
    status: 'Active',
    fieldMappings: [
      { sourceField: 'tender_id', targetField: 'tenderNumber', required: true, transformer: 'string' },
      { sourceField: 'work_name', targetField: 'name', required: true, transformer: 'string' },
      { sourceField: 'dept_name', targetField: 'department', required: true, transformer: 'string' },
      { sourceField: 'est_cost_inr', targetField: 'budget', required: true, transformer: 'number' },
      { sourceField: 'category', targetField: 'type', required: true, transformer: 'projectType' },
      { sourceField: 'commence_date', targetField: 'startDate', required: true, transformer: 'date' },
      { sourceField: 'completion_date', targetField: 'expectedCompletionDate', required: true, transformer: 'date' },
      { sourceField: 'excavation_depth_m', targetField: 'depthMeters', required: false, transformer: 'number' }
    ]
  },
  {
    id: 'ds-02',
    name: 'Nagpur Smart City SPV GIS GeoServer',
    url: 'https://geoserver.smartcitynagpur.gov.in/geoserver/wfs',
    type: 'GeoServer',
    authType: 'Bearer Token',
    endpoint: '/wfs?request=GetFeature&typename=infrastructure_projects',
    updateFrequency: 'Hourly',
    lastSynchronized: '2026-08-17 08:30:00',
    status: 'Active',
    fieldMappings: [
      { sourceField: 'proj_code', targetField: 'tenderNumber', required: true },
      { sourceField: 'title', targetField: 'name', required: true },
      { sourceField: 'geom', targetField: 'routeGeometry', required: true, transformer: 'geometry' },
      { sourceField: 'cost', targetField: 'budget', required: true, transformer: 'number' }
    ]
  }
];
